import {StyleSheet, Dimensions} from 'react-native';
import {color} from './../../theme/color';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo: {
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    marginBottom: 6,
  },
  appName: {fontSize: 26, color: 'black'},
  headerText: {
    color: 'white',
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.0516,
    fontWeight: '900',
  },
  loginImage: {
    width: windowWidth - 60,
    height: windowWidth * 0.63,
    alignSelf: 'center',
  },
  enableButton: {
    height: windowWidth * 0.16,
    borderRadius: windowWidth * 0.076,
    marginTop: windowWidth * 0.06,
    alignSelf: 'center',
    backgroundColor: color.secondaryColor,
    borderWidth: 0,
    marginBottom: windowWidth * 0.096,
  },
  button: {
    height: windowWidth * 0.16,
    borderRadius: windowWidth * 0.076,
    marginTop: windowWidth * 0.06,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderColor: color.lightGrey,
    borderWidth: 1.6,
    marginBottom: windowWidth * 0.096,
  },
  enableButtonText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    paddingHorizontal: windowWidth * 0.196,
  },
  buttonText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    fontWeight: '600',
    //padding: windowWidth * 0.196,
  },
  centerView: {
    flex: 0.65,
    marginHorizontal: windowWidth * 0.0416,
    marginTop: windowWidth * 0.5946,
  },
  subHeader: {
    color: color.primary,
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.06,
    marginLeft: windowWidth * 0.0264,
  },
  smallSubHeader: {
    color: color.textColor,
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.0516,
    marginTop: windowWidth * 0.01,
    marginLeft: windowWidth * 0.0264,
    shadowColor: 'black',
    shadowOpacity: 0.1,
    shadowOffset: {width: 1, height: 1},
    shadowRadius: 1,
    elevation: 0.16,
  },
  inputContainer: {
    borderBottomWidth: 0,
    borderRadius: windowWidth * 0.036,
    backgroundColor: color.inputBgClr,
  },
  inputStyle: {
    fontFamily: 'CenturyGothic',
    borderWidth: 0,
    borderBottomWidth: 0,
    height: windowWidth * 0.136,
    borderRadius: windowWidth * 0.136,
    marginLeft: windowWidth * 0.06,
  },
  inputLabel: {
    fontFamily: 'CenturyGothic-Bold',
    color: color.textColor,
    fontWeight: '400',
    marginBottom: 10,
  },
  forgotPasswordButonText: {
    color: '#0041c4',
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.04,
    marginLeft: windowWidth * 0.0264,
  },
  buttonView: {
    width: windowWidth * 0.69,
    height: windowWidth * 0.126,
    // borderWidth: 1,
    borderColor: '#f59459',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: windowWidth * 0.0626,
    backgroundColor: color.primary,
    borderRadius: windowWidth * 0.046,
  },
  errorTextStyle: {
    fontFamily: 'CenturyGothic-Bold',
    fontWeight: 'bold',
    color: color.error,
    fontSize: windowWidth * 0.036,
    // marginTop: 0.016,
  },
});
