import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
import {color} from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.primaryBgColour,
    //justifyContent: "center",
    //alignItems: "center",
  },
  logo: {
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    marginBottom: 6,
  },
  mainLogo: {
    width: windowWidth * 0.36,
    height: windowWidth * 0.36,
    marginBottom: windowWidth * 0.06,
    alignSelf: 'center',
  },
  appName: {fontSize: 26, color: 'black'},
  topContainer: {flex: 0.5, backgroundColor: color.secondaryColor},
  centerContainer: {
    flex: 0.1,
    flexDirection: 'row',
    //backgroundColor: "pink",
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomContainer: {flex: 0.4, backgroundColor: 'transparent'},
  titleText: {
    fontFamily: 'CenturyGothic',
    fontSize: windowWidth * 0.051,
  },
  renderText: {
    textAlign: 'center',
    fontSize: windowWidth * 0.026,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic',
  },
  listTopView: {
    width: windowWidth,
    paddingVertical: windowWidth * 0.036,
    borderWidth: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: windowWidth * 0.036,
    // backgroundColor: "pink",
  },
  listTitle: {
    color: color.primary,
    fontWeight: 'normal',
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.0384,
  },
  cardView: {
    marginHorizontal: windowWidth * 0.036,
    borderRadius: windowWidth * 0.0306,
    marginTop: -windowWidth * 0.01946,
    flex: 1,
    flexDirection: 'column',
  },
  curveTopView: {
    flex: 0.1,
    borderWidth: 1.6,
    borderBottomWidth: 0,
    borderColor: color.appGreen,
    borderTopRightRadius: windowWidth * 0.0264,
    borderTopLeftRadius: windowWidth * 0.0264,
  },
  curveBlueTopView: {
    flex: 0.1,
    borderWidth: 1.6,
    borderBottomWidth: 0,
    borderColor: color.primary,
    borderTopRightRadius: windowWidth * 0.0264,
    borderTopLeftRadius: windowWidth * 0.0264,
  },
  normalTopView: {
    flex: 0.1,
    borderWidth: 0,
    borderBottomWidth: 0,
    borderColor: color.primary,
  },
  cardTopBorderView: {
    marginHorizontal: windowWidth * 0.036,
    borderRadius: windowWidth * 0.036,
    marginTop: -windowWidth * 0.01946,
  },
  innerCardView: {
    flex: 0.9,
    backgroundColor: 'white',
    flexDirection: 'row',
    padding: windowWidth * 0.031,
    //paddingHorizontal: windowWidth * 0.036,
    justifyContent: 'space-between',
    borderRadius: windowWidth * 0.036,
  },
  cardSubContainer: {flexDirection: 'row', alignItems: 'center'},
  listAmount: {
    color: 'green',
    fontSize: windowWidth * 0.046,
    fontFamily: 'CenturyGothic-Bold',
  },
  listcommunityText: {
    color: 'black',
    fontSize: windowWidth * 0.029,
    fontFamily: 'CenturyGothic',
  },
  listTime: {
    color: color.lightGrey,
    fontSize: windowWidth * 0.023,
    fontFamily: 'CenturyGothic',
    //marginLeft: -windowWidth * 0.023,
    //marginRight: windowWidth * 0.09,
  },
  listBalanceTitle: {
    color: 'black',
    textAlign: 'right',
    fontSize: windowWidth * 0.0376,
    fontFamily: 'CenturyGothic-Bold',
  },
  listBalanceText: {
    color: 'green',
    textAlign: 'right',
    fontSize: windowWidth * 0.0376,
    fontFamily: 'CenturyGothic-Bold',
  },
  coinsImage: {
    height: windowWidth * 0.07146,
    width: windowWidth * 0.07146,
    marginTop: windowWidth * 0.016,
    alignSelf: 'center',
  },
  iconView: {
    width: windowWidth * 0.096,
    height: windowWidth * 0.096,
    borderRadius: (windowWidth * 0.196) / 2,
    //borderWidth: 0.6,
    borderColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselContainer: {
    backgroundColor: color.primary,
    paddingVertical: windowWidth * 0.016,
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0416,
    fontFamily: 'CenturyGothic-Bold',
  },
  circularView: {
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{rotate: '180deg'}],
    //marginBottom: windowWidth * 0.06,
  },
  circularInnerView: {
    height: windowWidth * 0.36,
    width: windowWidth * 0.36,
    borderRadius: (windowWidth * 0.36) / 2,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    transform: [{rotate: '180deg'}],
  },
  circularSubText: {
    color: 'white',
    fontSize: windowWidth * 0.0296,
    fontFamily: 'CenturyGothic',
  },
  circularMainText: {
    color: 'white',
    fontSize: windowWidth * 0.063,
    fontFamily: 'CenturyGothic-Bold',
  },
  incomeView: {
    flexDirection: 'row',
    height: windowWidth * 0.16,
    width: windowWidth,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    //backgroundColor: "orange",
  },
  amountTypeView: {
    flexDirection: 'column',
    marginLeft: windowWidth * 0.016,
  },
  subAmount: {
    color: 'white',
    fontSize: windowWidth * 0.0396,
    fontFamily: 'CenturyGothic-Bold',
  },
  incomeType: {
    color: 'white',
    fontSize: windowWidth * 0.0236,
    fontFamily: 'CenturyGothic-Bold',
  },
  buttonGroup: {
    height: windowWidth * 0.136,
    width: windowWidth / 1.126,
    padding: windowWidth * 0.016,
    borderColor: 'transparent',
    backgroundColor: color.primaryBgColour,
  },
});
