import {StyleSheet, Dimensions} from 'react-native';
import {color} from './../../theme/color';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo: {
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    marginBottom: 6,
  },
  appName: {fontSize: 26, color: 'black'},
  headerText: {
    color: 'white',
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.0516,
    //fontWeight: 'bold',
  },
  loginImage: {
    width: windowWidth - 60,
    height: windowWidth * 0.63,
    alignSelf: 'center',
  },
  enableButton: {
    height: windowWidth * 0.16,
    borderRadius: windowWidth * 0.076,
    //marginTop: windowWidth * 0.06,
    alignSelf: 'center',
    backgroundColor: color.primary,
    borderWidth: 0,
    marginBottom: windowWidth * 0.096,
  },
  button: {
    height: windowWidth * 0.16,
    borderRadius: windowWidth * 0.076,
    marginTop: windowWidth * 0.06,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderColor: color.lightGrey,
    borderWidth: 1,
    marginBottom: windowWidth * 0.096,
    justifyContent: 'center',
    alignItems: 'center',
  },
  enableButtonText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    paddingHorizontal: windowWidth * 0.196,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    fontWeight: 'bold',
  },
  centerView: {
    flex: 0.75,
    marginHorizontal: windowWidth * 0.0416,
    marginTop: windowWidth * 0.0136,
  },
  subHeader: {
    color: color.secondaryColor,
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.09,
    marginLeft: windowWidth * 0.0264,
    fontWeight: 'bold',
  },
  smallSubHeader: {
    color: 'white',
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.036,
    marginTop: windowWidth * 0.01,
    marginLeft: windowWidth * 0.0264,
    fontWeight: 'bold',
  },
  inputContainer: {
    borderBottomWidth: 0,
    borderRadius: windowWidth * 0.036,
    backgroundColor: color.inputBgClr,
  },
  inputStyle: {
    fontFamily: 'CenturyGothic',
    borderWidth: 0,
    borderBottomWidth: 0,
    height: windowWidth * 0.136,
    borderRadius: windowWidth * 0.136,
    marginLeft: windowWidth * 0.06,
  },
  inputLabel: {
    fontFamily: 'CenturyGothic-Bold',
    color: 'white',
    fontWeight: '900',
    fontSize: windowWidth * 0.0416,
    marginBottom: windowWidth * 0.036,
    marginLeft: windowWidth * 0.036,
  },
  forgotPasswordButonText: {
    color: 'white',
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.04,
    marginLeft: windowWidth * 0.0264,
    fontWeight: 'bold',
  },
  buttonView: {
    width: windowWidth * 0.69,
    height: windowWidth * 0.126,
    // borderWidth: 1,
    borderColor: '#f59459',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: windowWidth * 0.0626,
    backgroundColor: color.primary,
    borderRadius: windowWidth * 0.046,
  },
  errorTextStyle: {
    fontFamily: 'CenturyGothic-Bold',
    color: color.error,
    fontSize: windowWidth * 0.036,
    fontWeight: 'bold',
    marginLeft: windowWidth * 0.036,
    marginTop: windowWidth * 0.036,
    textShadowColor: 'black',
    textShadowOffset: {width: 0.6, height: 0.6},
    textShadowRadius: 1,
  },
  continueBtn: {
    width: windowWidth / 1.516,
    height: windowWidth / 8.64,
    backgroundColor: color.secondaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: windowWidth * 0.06,
    marginBottom: windowWidth * 0.06,
    borderRadius: windowWidth * 0.06,
  },
  continueBtnText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    paddingHorizontal: windowWidth * 0.06,
    paddingVertical: windowWidth * 0.016,
    fontWeight: '600',
  },
  orText: {
    color: color.textColor,
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.05149,
    marginLeft: windowWidth * 0.0264,
    fontWeight: 'bold',
    alignSelf: 'center',
    textShadowColor: 'black',
    textShadowOffset: {width: 0.6, height: 0.6},
    textShadowRadius: 1,
  },
  linkedInBtn: {
    width: windowWidth / 1.316,
    height: windowWidth / 7.9,
    backgroundColor: '#0a65c2',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: windowWidth * 0.06,
    marginBottom: windowWidth * 0.06,
    flexDirection: 'row',
    justifyContent: 'center',
    //borderRadius: windowWidth * 0.06,
  },
  linkedInBtnIcon: {color: color.textColor, fontSize: windowWidth * 0.063},
  linkedInBtnText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    paddingVertical: windowWidth * 0.016,
    fontWeight: '600',
    marginLeft: windowWidth * 0.0163,
  },
});
