import {StyleSheet, Dimensions} from 'react-native';
import {color} from './../../theme/color';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.background,
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  topContainer: {
    flex: 0.4,
    backgroundColor: color.secondaryColor,
    height: windowHeight / 3.06,
  },
  multiBtn: {
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: windowWidth * 0.0136,
    margin: windowWidth * 0.0136,
    backgroundColor: 'pink',
  },
  multiBtnText: {
    fontSize: windowWidth * 0.0376,
    color: color.textColor,
    fontFamily: 'CenturyGothic',
    padding: windowWidth * 0.0163,
    paddingHorizontal: windowWidth * 0.036,
  },
  activeMultiBtn: {
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: windowWidth * 0.0136,
    margin: windowWidth * 0.0136,
  },
  bottomContainer: {
    flex: 0.6,
    backgroundColor: color.background,
  },
  activeMultiBtn: {
    borderWidth: 0,
    borderColor: 'black',
    borderRadius: windowWidth * 0.0136,
    margin: windowWidth * 0.0136,
    opacity: 0.6,
  },
  commonBlackTitle: {
    fontFamily: 'CenturyGothic',
    color: 'black',
    marginHorizontal: windowWidth * 0.036,
    fontSize: windowWidth * 0.0516,
  },
  commonGreyTitle: {
    fontFamily: 'CenturyGothic',
    color: color.greyText,
    marginHorizontal: windowWidth * 0.036,
    fontSize: windowWidth * 0.0436,
  },
  subTitle: {
    fontFamily: 'CenturyGothic',
    color: 'black',
    marginHorizontal: windowWidth * 0.036,
    fontSize: windowWidth * 0.0436,
  },
  row: {
    width: windowWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: windowWidth * 0.036,
    paddingLeft: windowWidth * 0.016,
  },
  rowImage: {
    width: windowWidth * 0.136,
    height: windowWidth * 0.136,
    borderRadius: (windowWidth * 0.136) / 2,
  },
  instructorName: {
    fontFamily: 'CenturyGothic-Bold',
    color: color.blackText,
    fontWeight: '900',
    fontSize: windowWidth * 0.0436,
  },
  ratingText: {
    fontFamily: 'CenturyGothic',
    color: color.blackText,
    fontWeight: '600',
    fontSize: windowWidth * 0.0436,
  },
  activityIcon: {
    fontSize: windowWidth * 0.0936,
    color: color.text,
    alignSelf: 'center',
  },
  listTitle: {
    fontFamily: 'CenturyGothic',
    color: color.blackText,
    fontSize: windowWidth * 0.0416,
  },
  iconView: {
    width: windowWidth * 0.096,
    height: windowWidth * 0.096,
    borderRadius: (windowWidth * 0.96) / 2,
    backgroundColor: color.paleYellow,
  },
  rowText: {
    fontFamily: 'CenturyGothic',
    color: color.blackText,
    fontSize: windowWidth * 0.0416,
    marginLeft: windowWidth * 0.036,
    width: windowWidth / 1.6,
  },
  rowIcon: {
    fontSize: windowWidth * 0.0516,
    color: color.blackText,
    alignSelf: 'center',
    textAlign: 'center',
    textAlignVertical: 'center',
    marginTop: windowWidth * 0.01963,
  },
  searchBarContainer: {
    backgroundColor: color.secondaryColor,
    width: windowWidth / 1.06,
    borderBottomWidth: 0,
  },
  modalBox: {
    flexDirection: 'column',
    width: windowWidth,
    //height: windowHeight / 1.136,
    //borderTopLeftRadius: windowWidth * 0.106,
    //borderTopRightRadius: windowWidth * 0.106,
    backgroundColor: color.whiteBg,
    alignSelf: 'center',
    justifyContent: 'flex-end',
    //marginTop: windowWidth + windowWidth * 0.136,
    borderWidth: 0,
    borderColor: 'orange',
    backgroundColor: 'white',
    //justifyContent: 'center',
    //alignItems: 'flex-end'
    flex: 1
  },
  sortText: {
    fontFamily: 'CenturyGothic',
    color: color.appGreen,
    fontSize: windowWidth * 0.0416,
    padding: windowWidth * 0.036,
  },
  filterTitle: {
    fontFamily: 'CenturyGothic',
    color: color.appGreen,
    fontSize: windowWidth * 0.0436,
    alignSelf: 'flex-start',
    marginLeft: windowWidth * 0.036,
  },
  inputStyle: {
    fontFamily: 'CenturyGothic',
    fontSize: windowWidth * 0.0416,
  },
  inputLabel: {
    fontFamily: 'CenturyGothic',
    color: color.blackText,
    marginLeft: windowWidth * 0.036,
    fontSize: windowWidth * 0.0416,
    marginBottom: -windowWidth * 0.006,
  },
  dropdownArrow: {
    color: color.greyText,
    fontSize: windowWidth * 0.06,
    alignSelf: 'center',
  },
  sepDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: windowWidth * 0.036,
  },
  inputDropdownStyle: {
    fontFamily: 'CenturyGothic',
    fontSize: windowWidth * 0.0416,
    marginVertical: windowWidth * 0.036,
    marginLeft: windowWidth * 0.0136,
    color: color.lightGrey,
  },
  inputDropdownLabel: {
    fontFamily: 'CenturyGothic',
    color: 'black',
    fontWeight: '900',
    fontSize: windowWidth * 0.0416,
    marginBottom: -windowWidth * 0.006,
  },
  menuRowStyle: {
    borderBottomWidth: 0.96,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filterButton: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: color.appOrange,
    marginBottom: windowWidth * 0.06,
    borderWidth: 0,
    borderRadius: windowWidth * 0.0636,
  },
  jobTypeButton: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    //backgroundColor: color.secondaryColor,
    marginBottom: windowWidth * 0.06,
    height: windowWidth * 0.09636,
    width: windowWidth * 0.36,
    marginRight: windowWidth * 0.06,
    borderRadius: windowWidth * 0.0136,
    flexDirection: 'row'
  },
  jobTypeTitle: {
    fontFamily: 'CenturyGothic',
    color: 'black',
    fontSize: windowWidth * 0.0436,
  },
  buttonGroupView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: windowWidth * 0.036,
  },
});
