import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
import {color} from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.background,
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  logo: {
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    marginBottom: 6,
  },
  appName: {fontSize: 26, color: 'black'},
  flatListContainer: {
    paddingTop: windowWidth * 0.0296,
    alignItems: 'center',
  },
  listImageView: {
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    borderWidth: 0,
    justifyContent: 'space-around',
    margin: windowWidth * 0.0096,
    borderRadius: windowWidth * 0.0196,
  },
  listImageStyle: {
    flexDirection: 'row',
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    borderRadius: windowWidth * 0.0196,
    alignItems: 'flex-end',
    padding: windowWidth * 0.0246,
  },
  listTitleStyle: {
    color: color.textColor,
    fontSize: windowWidth * 0.046,
    fontFamily: 'CenturyGothic-Bold',
    textShadowColor: 'black',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 1,
  },
  searchBarContainer: {
    backgroundColor: color.primaryBgColour,
    width: windowWidth / 1.06,
    borderBottomWidth: 0,
  },
  filterList: {
    width: windowWidth - 40,
    backgroundColor: 'white',
    padding: windowWidth * 0.0316,
    alignSelf: 'center',
    marginTop: -windowWidth * 0.016,
  },
  filterListText: {
    fontFamily: 'CenturyGothic',
    marginLeft: windowWidth * 0.066,
  },
  button: {
    width: windowWidth / 1.6,
    height: windowWidth * 0.156,
    borderRadius: windowWidth * 0.076,
    marginTop: windowWidth * 0.069,
    marginBottom: windowWidth * 0.136,
    alignSelf: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: windowWidth * 0.049,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
  },
  inviteView: {
    width: windowWidth - windowWidth * 0.0376,
    minHeight: windowWidth / 2.4996,
    borderRadius: windowWidth * 0.036,
    backgroundColor: color.appGreen,
    marginVertical: windowWidth * 0.036,
    padding: windowWidth * 0.0416,
    flexDirection: 'column',
    justifyContent: 'space-around',
  },
  inviteTitle: {
    color: color.textColor,
    fontSize: windowWidth * 0.0536,
    fontFamily: 'CenturyGothic-Bold',
  },
  inviteInnerView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inviteDescription: {
    color: color.textColor,
    fontSize: windowWidth * 0.0416,
    fontFamily: 'CenturyGothic',
    width: windowWidth / 1.946,
  },
  inviteButton: {
    backgroundColor: 'white',
    fontSize: windowWidth * 0.046,
    fontFamily: 'CenturyGothic',
    width: windowWidth * 0.316,
    height: windowWidth * 0.0996,
    borderRadius: windowWidth * 0.036,
    alignItems: 'center',
    justifyContent: 'center',
  },
  getStarted: {
    color: color.appGreen,
    fontSize: windowWidth * 0.0416,
    fontFamily: 'CenturyGothic',
  },
  gridView: {
    width: windowWidth / 2.1496,
    height: windowWidth / 2.496,
    borderRadius: windowWidth * 0.036,
    backgroundColor: color.appGreen,
    margin: windowWidth * 0.01136,
    padding: windowWidth * 0.036,
  },
  moreIconView: {
    width: windowWidth / 9,
    height: windowWidth / 9,
    borderRadius: windowWidth / 6 / 2,
    backgroundColor: '#f7dab6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  moreIcons: {width: windowWidth * 0.06, height: windowWidth * 0.06},
  moreTitle: {
    color: color.textColor,
    fontSize: windowWidth * 0.0536,
    alignSelf: 'flex-start',
    marginVertical: windowWidth * 0.036,
    fontFamily: 'CenturyGothic-Bold',
  },
  moreDescription: {
    color: color.textColor,
    fontSize: windowWidth * 0.0336,
    alignSelf: 'flex-start',
    fontFamily: 'CenturyGothic',
    fontWeight: '500',
  },
  mainImage: {
    width: windowWidth,
    height: windowHeight / 1.63,
    borderBottomLeftRadius: windowWidth * 0.136,
    borderBottomRightRadius: windowWidth * 0.136,
  },
  title: {
    color: color.blackText,
    fontSize: windowWidth * 0.0936,
    fontFamily: 'CenturyGothic-Bold',
    textAlign: 'center',
    marginTop: windowWidth * 0.06,
  },
  buttonView: {
    backgroundColor: color.appGreen,
    fontSize: windowWidth * 0.046,
    fontFamily: 'CenturyGothic',
    width: windowWidth * 0.6,
    height: windowWidth * 0.136,
    borderRadius: windowWidth * 0.09,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: windowWidth * 0.06,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  letsGo: {
    color: color.textColor,
    fontSize: windowWidth * 0.056,
    fontFamily: 'CenturyGothic-Bold',
  },
  iconView: {
    width: windowWidth * 0.096,
    height: windowWidth * 0.096,
    borderRadius: (windowWidth * 0.096) / 2,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    fontSize: windowWidth * 0.06636,
    alignSelf: 'center',
  },
});
