import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
import {color} from '../../theme';
import {colors} from 'react-native-elements';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.primaryBgColour,
    //justifyContent: "center",
    //alignItems: "center",
  },
  logo: {
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    marginBottom: 6,
  },
  appName: {fontSize: 26, color: 'black'},
  title: {
    fontFamily: 'CenturyGothic',
    fontSize: windowWidth * 0.046,
    marginLeft: windowWidth * 0.0169,
  },
  titleText: {
    color: color.primary,
    fontFamily: 'CenturyGothic-Bold',
    alignSelf: 'center',
    fontSize: windowWidth * 0.069,
    textShadowColor: color.primaryColor,
    textShadowOffset: {width: 1, height: 1.6},
    textShadowRadius: 1,
    marginBottom: windowWidth * 0.16,
  },
  topProfileContainer: {
    width: windowWidth,
    padding: windowWidth * 0.06,
  },
  name: {
    color: color.secondaryColor,
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.07699,
  },
  locationIcon: {
    color: color.greyText,
    fontSize: windowWidth * 0.0416,
    marginTop: windowWidth * 0.0069,
    marginRight: windowWidth * 0.016,
  },
  locationText: {
    color: '#939aa0',
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.0416,
  },
  profilePic: {
    width: windowWidth / 1.12,
    height: windowWidth / 1.536,
    padding: windowWidth * 0.016,
  },
  picButton: {
    backgroundColor: color.secondaryColor,
    alignSelf: 'flex-end',
    borderRadius: windowWidth * 0.096,
  },
  followText: {
    color: color.textColor,
    fontFamily: 'CenturyGothic',
    fontSize: windowWidth * 0.036,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  inputContainer: {
    borderBottomWidth: 0,
    backgroundColor: color.inputBgClr,
  },
  inputStyle: {
    fontFamily: 'CenturyGothic',
    borderWidth: 0,
    borderBottomWidth: 0,
    height: windowWidth * 0.136,
    fontSize: windowWidth * 0.0416,
  },
  inputLabel: {
    fontFamily: 'CenturyGothic-Bold',
    color: '#c1c7e0',
    fontWeight: '400',
    marginBottom: 10,
  },
  button: {
    height: windowWidth * 0.16,
    marginTop: windowWidth * 0.06,
    marginBottom: windowWidth * 0.096,
    marginHorizontal: windowWidth * 0.0199,
    borderRadius: windowWidth * 0.16,
  },
  buttonText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    //padding: windowWidth * 0.196,
  },
  inputIcon: {
    color: color.greyBg,
    marginRight: windowWidth * 0.0146,
  },
  modalBox: {
    backgroundColor: 'white',
    height: windowWidth / 1.56,
    borderRadius: windowWidth * 0.006,
  },
  avatarTitle: {
    color: color.appGreen,
    fontSize: windowWidth * 0.0469,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    // paddingVertical: windowWidth * 0.16,
  },
  chooseOptionTitle: {
    color: color.blackText,
    fontSize: windowWidth * 0.0436,
    fontFamily: 'CenturyGothic',
  },
  modalButton: {
    height: windowWidth * 0.16,
    marginTop: windowWidth * 0.0416,
    marginBottom: windowWidth * 0.006,
    marginHorizontal: windowWidth * 0.0199,
    //borderRadius: windowWidth * 0.16,
  },
  avatarCancelBtn: {
    width: windowWidth / 1.6,
    height: windowWidth / 9,
    backgroundColor: color.secondaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: windowWidth * 0.06,
    borderRadius: windowWidth * 0.06,
  },
  avatarbuttonText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    paddingHorizontal: windowWidth * 0.06,
    paddingVertical: windowWidth * 0.016,
  },
  datePicker: {
    borderTopWidth: 0,
    borderStyle: null,
    borderRadius: 0,
    height: windowWidth * 0.15,
    width: windowWidth - windowWidth * 0.06,
    backgroundColor: 'transparent',
    //marginHorizontal: windowWidth * 0.36,
    marginLeft: windowWidth * 0.061,
    marginTop: windowWidth * 0.01,
    borderBottomWidth: 0,
    borderBottomColor: color.lineColor,
    borderColor: color.lineColor,
    alignSelf: 'center',
  },
  datePickerInput: {
    backgroundColor: 'transparent',
    top: 0,
    bottom: 0,
    height: windowHeight / 15.6,
    minHeight: 44,
    minWidth: windowWidth / 3.6,
    width: windowWidth * 0.06,
    borderRadius: 0,
    borderWidth: 0,
    borderColor: color.lineColor,
    color: 'pink',
    fontSize: windowWidth * 0.0416,
    marginTop: windowWidth * 0.076,
    alignItems: 'flex-start',
    paddingLeft: windowWidth * 0.016,
    borderBottomWidth: 0,
    borderBottomColor: color.lineColor,
    fontFamily: 'CenturyGothic',
  },
  datePickerLine: {
    height: 0.6,
    backgroundColor: color.blackText,
    width: windowWidth - windowWidth * 0.1136,
    alignSelf: 'center',
  },
  genderPlaceHolderStyle: {
    fontSize: windowWidth * 0.0416,
    marginLeft: windowWidth * 0.00636,
    marginBottom: windowWidth * 0.036,
    color: color.lightGrey,
    fontFamily: 'CenturyGothic',
  },
  genderTextStyle: {
    fontSize: windowWidth * 0.0416,
    marginLeft: windowWidth * 0.00636,
    marginBottom: windowWidth * 0.036,
    color: color.blackText,
    fontFamily: 'CenturyGothic',
  },
  pickerContainer: {
    marginHorizontal: windowWidth * 0.0316,
    borderBottomWidth: 0.6,
    borderColor: color.blackText,
    marginVertical: windowWidth * 0.0416,
  },
  pickerStyle: {minHeight: 44, width: windowWidth / 1.09},
  pickerItem: {
    fontSize: windowWidth * 0.0416,
    marginLeft: windowWidth * 0.019,
    fontFamily: 'CenturyGothic',
  },
  modalShareBox: {
    width: windowWidth / 1.264,
    backgroundColor: 'white',
    padding: windowWidth * 0.06,
    borderRadius: windowWidth * 0.0164,
    alignSelf: 'center',
  },
  modalShareView: {
    flexDirection: 'row',
    backgroundColor: 'white',
    padding: windowWidth * 0.0146,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalShareText: {
    fontSize: windowWidth * 0.0416,
    fontFamily: 'CenturyGothic',
    color: 'black',
    //alignSelf: "center",
    textAlign: 'left',
    marginVertical: windowWidth * 0.036,
  },
  modalShareButtonText: {
    fontSize: windowWidth * 0.0436,
    fontFamily: 'CenturyGothic',
    color: 'black',
    //alignSelf: "center",
    alignSelf: 'center',
  },
  errorTextStyle: {
    fontFamily: 'CenturyGothic',
    color: color.alertRed,
    fontSize: windowWidth * 0.036,
    //marginLeft: windowWidth * 0.0769,
    // marginTop: 0.016,
  },
  normalErrorTextStyle: {
    fontFamily: 'CenturyGothic',
    color: color.alertRed,
    fontSize: windowWidth * 0.036,
    //marginLeft: windowWidth * 0.0769,
    marginTop: -windowWidth * 0.16,
  },
});
