import {palette} from './palette';

export const color = {
  transparent: 'rgba(0, 0, 0, 0)',
  background: palette.white,
  primary: palette.cyanBlue,
  primaryDarker: palette.orangeDarker,
  line: palette.offWhite,
  text: palette.white,
  lightGrey: palette.lightGrey,
  error: palette.angry,
  lineColor: palette.inputLineGrey,
  buttonGradient: ['#c63894', '#d9465c', '#f58559'],
  Gradient: ['#e1625b', '#ef7b5a'],
  primaryColor: palette.primaryOrange,
  primaryGradient: [palette.cyanBlue, palette.cyanBlue],
  primaryButtonGradient: [palette.cyanBlue, palette.cyanBlue, palette.cyanBlue],
  inputBgClr: palette.lightGreyBg,
  textColor: palette.white,
  blackText: palette.neroBlack,
  greyBg: palette.ashGrey,
  primaryBgColour: palette.primaryBgColour,
  primaryYellow: palette.primaryYellow,
  secondaryOrange: palette.moderateOrange,
  greyText: palette.nobelGrey,
  successGreen: palette.fernGreen,
  alertRed: palette.tomatoRed,
  warnOrange: palette.neonOrange,
  sliverColor: palette.silverSwan,
  appGreen: palette.mainGreen,
  appOrange: palette.yellowish,
  secondaryColor: palette.yellowish,
  paleYellow: palette.paleYellowish,
  tonerGrey: palette.tonerGrey,
};
