import {StyleSheet, Dimensions} from 'react-native';
import {color} from '../../theme/color';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    // justifyContent: "center",
    // alignItems: "center",
  },
  logo: {
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    marginBottom: 6,
  },
  appName: {fontSize: 26, color: 'black'},
  headerText: {
    color: color.textColor,
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.0516,
  },
  subContainer: {
    marginHorizontal: windowWidth * 0.0416,
    marginTop: windowWidth * 0.1964,
  },
  contentText: {
    color: color.textColor,
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.0416,
    marginTop: windowWidth * 0.19649,
    marginHorizontal: windowWidth * 0.069,
    alignSelf: 'center',
    textAlign: 'center',
    shadowColor: 'black',
    shadowOpacity: 0.1,
    shadowOffset: {width: 1, height: 1},
    shadowRadius: 1,
    elevation: 0.16,
  },
  inputContainer: {
    borderBottomWidth: 1,
    borderColor: color.line,
    backgroundColor: color.inputBgClr,
  },
  inputStyle: {
    fontFamily: 'CenturyGothic',
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: color.line,
    height: windowWidth * 0.136,
    textAlign: 'center',
    fontWeight: '900',
    fontSize: windowWidth * 0.046,
    color: color.blackText,
  },
  inputLabel: {
    // fontFamily: "CenturyGothic-Bold",
    // color: "#c1c7e0",
    // fontWeight: "400",
    // marginBottom: 10,
  },
  buttonView: {
    width: windowWidth * 0.864,
    height: windowWidth * 0.126,
    borderRadius: windowWidth * 0.0136,
    borderColor: color.secondaryColor,
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: windowWidth * 0.0326,
    backgroundColor: color.inputBgClr,
    //borderRadius: windowWidth * 0.046,
  },
  buttonText: {
    color: '#003237',
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.046,
    alignSelf: 'center',
    fontWeight: '600',
  },
  bottomImage: {
    //position: "absolute",
    width: windowWidth,
    height: windowWidth * 0.63,
    alignSelf: 'flex-end',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  resetPwdModal: {
    width: windowWidth - 30,
    height: windowWidth / 1.6,
    backgroundColor: color.textColor,
    justifyContent: 'center',
  },
  subHeader: {
    color: color.primary,
    fontFamily: 'CenturyGothic',
    fontSize: windowWidth * 0.0496,
    alignSelf: 'center',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  centerContent: {
    color: color.primary,
    fontFamily: 'CenturyGothic',
    fontSize: windowWidth * 0.0384,
    marginTop: windowWidth * 0.036,
    marginHorizontal: windowWidth * 0.16,
    alignSelf: 'center',
    textAlign: 'center',
  },
  modalButton: {
    width: windowWidth * 0.69,
    height: windowWidth * 0.126,
    borderWidth: 1,
    borderColor: '#f59459',
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: windowWidth * 0.0326,
    //backgroundColor: color.primary,
    //borderRadius: windowWidth * 0.046,
  },
  modalButtonText: {
    //color: "#f59459",
    color: color.primary,
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.046,
    alignSelf: 'center',
  },
  errorTextStyle: {
    fontFamily: 'CenturyGothic-Bold',
    color: color.error,
    fontSize: windowWidth * 0.036,
    textAlign: 'center',
    fontWeight: 'bold',
    // marginTop: 0.016,
  },
});
