import {StyleSheet, Dimensions} from 'react-native';
import {color} from '../../theme';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo: {
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    marginBottom: 6,
  },
  appName: {fontSize: 26, color: 'black'},
  headerText: {
    color: 'white',
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.0516,
    //fontWeight: 'bold',
  },
  enableButton: {
    height: windowWidth * 0.16,
    borderRadius: windowWidth * 0.076,
    marginTop: windowWidth * 0.06,
    alignSelf: 'center',
    backgroundColor: color.secondaryColor,
    borderWidth: 0,
    marginBottom: windowWidth * 0.06,
  },
  button: {
    height: windowWidth * 0.16,
    borderRadius: windowWidth * 0.076,
    marginTop: windowWidth * 0.06,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderColor: color.lightGrey,
    borderWidth: 1,
    marginBottom: windowWidth * 0.06,
  },
  enableButtonText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    fontWeight: '600',
    paddingHorizontal: windowWidth * 0.196,
  },
  buttonText: {
    color: 'black',
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    fontWeight: '600',
    //padding: windowWidth * 0.196,
  },
  checkBox: {
    width: windowWidth * 0.09,
    height: windowWidth * 0.09,
    marginTop: windowWidth * 0.03,
  },
  checkBoxText: {
    fontSize: windowWidth * 0.0416,
    //marginLeft: windowWidth * 0.01,
    marginTop: windowWidth * 0.036,
    color: color.lightGrey,
    fontFamily: 'CenturyGothic',
  },
  genderPlaceHolderStyle: {
    fontSize: windowWidth * 0.0416,
    //marginLeft: windowWidth * 0.01,
    marginTop: windowWidth * 0.036,
    color: color.lightGrey,
    fontFamily: 'CenturyGothic',
    marginLeft: windowWidth * 0.019946,
  },
  genderTextStyle: {
    fontSize: windowWidth * 0.0416,
    //marginLeft: windowWidth * 0.01,
    marginTop: windowWidth * 0.036,
    color: color.blackText,
    fontFamily: 'CenturyGothic',
    marginLeft: windowWidth * 0.019946,
  },
  pickerContainer: {
    minHeight: 44,
    marginHorizontal: windowWidth * 0.06,
    borderBottomWidth: 2.1,
    borderColor: color.lineColor,
    marginTop: windowWidth * 0.046,
  },
  pickerStyle: {minHeight: 44, width: windowWidth / 1.09},
  pickerItem: {
    fontSize: windowWidth * 0.0416,
    marginLeft: windowWidth * 0.019,
    fontFamily: 'CenturyGothic',
  },
  datePicker: {
    borderTopWidth: 0,
    borderStyle: null,
    borderRadius: 0,
    height: windowWidth * 0.15,
    width: windowWidth * 0.884,
    backgroundColor: 'transparent',
    marginHorizontal: windowWidth * 0.1,
    marginLeft: windowWidth * 0.061,
    marginTop: windowWidth * 0.01,
    borderBottomWidth: 0,
    borderBottomColor: color.lineColor,
    borderColor: color.lineColor,
  },
  datePickerInput: {
    backgroundColor: 'white',
    top: 0,
    bottom: 0,
    height: windowHeight / 15.6,
    minHeight: 44,
    minWidth: windowWidth / 3.6,
    width: 10,
    borderRadius: 0,
    borderWidth: 0,
    borderColor: color.lineColor,
    color: 'pink',
    fontSize: windowWidth * 0.04169,
    marginTop: windowWidth * 0.076,
    alignItems: 'flex-start',
    paddingLeft: windowWidth * 0.016,
    borderBottomWidth: 0,
    borderBottomColor: color.lineColor,
    //fontFamily: "OpenSans",
  },
  datePickerLine: {
    height: 1.999996,
    backgroundColor: color.lineColor,
    width: windowWidth - windowWidth * 0.1136,
    alignSelf: 'center',
  },
  errorTextStyle: {
    fontFamily: 'CenturyGothic',
    color: color.alertRed,
    fontSize: windowWidth * 0.036,
    marginLeft: windowWidth * 0.0769,
    // marginTop: 0.016,
  },
  phoneErrorTextStyle: {
    fontFamily: 'CenturyGothic',
    color: color.alertRed,
    fontSize: windowWidth * 0.036,
    marginLeft: windowWidth * 0.0769,
    marginTop: windowWidth * 0.06,
    marginBottom: -windowWidth * 0.0316,
  },
  modalShareBox: {
    width: windowWidth / 1.264,
    backgroundColor: 'white',
    padding: windowWidth * 0.06,
    borderRadius: windowWidth * 0.0164,
    alignSelf: 'center',
  },
  modalShareView: {
    flexDirection: 'row',
    backgroundColor: 'white',
    padding: windowWidth * 0.0146,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalShareText: {
    fontSize: windowWidth * 0.0416,
    fontFamily: 'CenturyGothic',
    color: 'black',
    //alignSelf: "center",
    textAlign: 'left',
    marginVertical: windowWidth * 0.036,
  },
  modalShareButtonText: {
    fontSize: windowWidth * 0.0436,
    fontFamily: 'CenturyGothic',
    color: 'black',
    //alignSelf: "center",
    alignSelf: 'center',
  },
  profilePic: {
    width: windowWidth / 3.16,
    height: windowWidth / 3.16,
    borderRadius: windowWidth / 3.16 / 2,
    backgroundColor: color.lightGrey,
    alignSelf: 'center',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  picButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: windowWidth * 0.06,
  },
  profilePicText: {
    fontSize: windowWidth * 0.0436,
    fontFamily: 'CenturyGothic-Bold',
    fontWeight: '600',
    color: color.secondaryColor,
    padding: windowWidth * 0.06,
    paddingTop: 0,
  },
  modalBox: {
    backgroundColor: 'white',
    height: windowWidth / 1.56,
    borderRadius: windowWidth * 0.006,
  },
  avatarTitle: {
    color: color.appGreen,
    fontSize: windowWidth * 0.0469,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    // paddingVertical: windowWidth * 0.16,
  },
  chooseOptionTitle: {
    color: color.blackText,
    fontSize: windowWidth * 0.0436,
    fontFamily: 'CenturyGothic',
  },
  modalButton: {
    height: windowWidth * 0.16,
    marginTop: windowWidth * 0.0416,
    marginBottom: windowWidth * 0.006,
    marginHorizontal: windowWidth * 0.0199,
    //borderRadius: windowWidth * 0.16,
  },
  avatarCancelBtn: {
    width: windowWidth / 1.6,
    height: windowWidth / 9,
    backgroundColor: color.secondaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: windowWidth * 0.06,
    borderRadius: windowWidth * 0.06,
  },
  avatarbuttonText: {
    color: color.textColor,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    paddingHorizontal: windowWidth * 0.06,
    paddingVertical: windowWidth * 0.016,
  },
});
