import {StyleSheet, Dimensions} from 'react-native';
import {color} from './../../theme/color';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.background,
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  topContainer: {
    flex: 0.24,
    backgroundColor: color.secondaryColor,
    // justifyContent: 'center',
    // alignItems: 'center',
    padding: windowWidth * 0.06,
  },
  multiBtn: {
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: windowWidth * 0.0136,
    margin: windowWidth * 0.0136,
    backgroundColor: 'pink',
  },
  multiBtnText: {
    fontSize: windowWidth * 0.0376,
    color: color.textColor,
    fontFamily: 'CenturyGothic',
    padding: windowWidth * 0.0163,
    paddingHorizontal: windowWidth * 0.036,
  },
  activeMultiBtn: {
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: windowWidth * 0.0136,
    margin: windowWidth * 0.0136,
  },
  bottomContainer: {
    flex: 0.86,
    backgroundColor: color.background,
  },
  activeMultiBtn: {
    borderWidth: 0,
    borderColor: 'black',
    borderRadius: windowWidth * 0.0136,
    margin: windowWidth * 0.0136,
    opacity: 0.6,
  },
  commonBlackTitle: {
    fontFamily: 'CenturyGothic-Bold',
    color: 'black',
    fontWeight: '900',
    marginHorizontal: windowWidth * 0.036,
    fontSize: windowWidth * 0.0996,
  },
  commonGreyTitle: {
    fontFamily: 'CenturyGothic-Bold',
    color: color.greyText,
    fontWeight: '900',
    marginHorizontal: windowWidth * 0.036,
    fontSize: windowWidth * 0.0436,
  },

  row: {
    backgroundColor: 'white',
    borderRadius: windowWidth * 0.036,
    padding: windowWidth * 0.036,
    marginBottom: windowWidth * 0.06,
  },
  rowImage: {
    width: windowWidth * 0.36,
    height: windowWidth * 0.36,
    //borderRadius: (windowWidth * 0.136) / 2,
  },
  rowTitle: {
    fontFamily: 'CenturyGothic-Bold',
    color: color.blackText,
    fontWeight: '900',
    fontSize: windowWidth * 0.06,
  },
  rowDescription: {
    fontFamily: 'CenturyGothic',
    color: color.blackText,
    fontSize: windowWidth * 0.0416,
  },
  ratingText: {
    fontFamily: 'CenturyGothic',
    color: color.blackText,
    fontWeight: '600',
    fontSize: windowWidth * 0.0436,
  },
  activityIcon: {
    fontSize: windowWidth * 0.0936,
    color: color.text,
    alignSelf: 'center',
  },
  listTitle: {
    fontFamily: 'CenturyGothic-Bold',
    color: color.blackText,
    fontWeight: '900',
    fontSize: windowWidth * 0.0416,
  },
  iconView: {
    width: windowWidth * 0.096,
    height: windowWidth * 0.096,
    borderRadius: (windowWidth * 0.96) / 2,
    backgroundColor: color.greyBg,
  },
  rowText: {
    fontFamily: 'CenturyGothic',
    color: color.blackText,
    fontWeight: '900',
    fontSize: windowWidth * 0.0416,
    marginLeft: windowWidth * 0.036,
  },
  rowIcon: {
    fontSize: windowWidth * 0.0516,
    color: color.blackText,
    alignSelf: 'center',
    textAlign: 'center',
    textAlignVertical: 'center',
    marginTop: windowWidth * 0.01963,
  },
  submitButton: {
    width: windowWidth / 1.946,
    height: windowWidth * 0.136,
    backgroundColor: color.appGreen,
    alignSelf: 'center',
    marginBottom: windowWidth * 0.096,
    borderRadius: windowWidth * 0.136,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitText: {
    fontFamily: 'CenturyGothic-Bold',
    color: color.text,
    fontSize: windowWidth * 0.0419,
    alignSelf: 'center',
    fontFamily: 'CenturyGothic-Bold',
    fontWeight: '600',
  },
  suitCaseBox: {
    width: windowWidth * 0.246,
    height: windowWidth * 0.246,
    borderRadius: windowWidth * 0.06,
    backgroundColor: color.paleYellow,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  suitCase: {width: windowWidth * 0.136, height: windowWidth * 0.136},
  subTitle: {
    fontFamily: 'CenturyGothic',
    color: color.blackText,
    // marginHorizontal: windowWidth * 0.036,
    fontSize: windowWidth * 0.0516,
    // marginTop: windowWidth * 0.036,
  },
  topButton: {
    backgroundColor: color.appGreen,
    minWidth: windowWidth * 0.246,
    height: windowWidth * 0.096,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: windowWidth * 0.036,
  },
  topButtonText: {
    fontFamily: 'CenturyGothic',
    color: color.textColor,
    fontSize: windowWidth * 0.0416,
  },
  infoSubTitle: {
    fontFamily: 'CenturyGothic',
    color: color.appGreen,
    fontSize: windowWidth * 0.0516,
    marginVertical: windowWidth * 0.036,
  },
  infoDescription: {
    fontFamily: 'CenturyGothic',
    color: color.appGreen,
    fontSize: windowWidth * 0.046,
    lineHeight: windowWidth * 0.0736,
  },
  qualificationText: {
    fontFamily: 'CenturyGothic',
    color: color.appGreen,
    fontSize: windowWidth * 0.0436,
    alignSelf: 'flex-start',
    width: windowWidth - windowWidth * 0.1136,
  },
  dot: {
    width: windowWidth * 0.0306,
    height: windowWidth * 0.0306,
    borderRadius: (windowWidth * 0.0306) / 2,
    backgroundColor: color.appGreen,
    // alignSelf: 'center',
    marginRight: windowWidth * 0.036,
  },
  button: {
    flex: 1,
    width: windowWidth / 1.136,
    height: windowWidth * 0.136,
    borderRadius: (windowWidth * 0.06) / 2,
    backgroundColor: color.appGreen,
    marginVertical: windowWidth * 0.0306,
    marginBottom: windowWidth * 0.136,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  buttonText: {
    color: color.textColor,
    fontFamily: 'CenturyGothic-Bold',
    fontSize: windowWidth * 0.0436,
  },
  handImage: {
    fontSize: windowWidth * 0.06,
    color: color.textColor,
    marginRight: windowWidth * 0.036,
  },
  handImageActive: {
    fontSize: windowWidth * 0.06,
    color: color.secondaryColor,
    marginRight: windowWidth * 0.036,
  },
});
