require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ClimateX' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  pod 'RNSound', :path => '../node_modules/react-native-sound'



  target 'ClimateXTests' do
    inherit! :complete
    # Pods for testing
  end

  "${PODS_CONFIGURATION_BUILD_DIR}/lottie-ios"
  "${PODS_CONFIGURATION_BUILD_DIR}/lottie-react-native" 
  
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera/Permission-Camera.podspec"
  
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
 # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end