import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
import {color} from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    //justifyContent: "center",
    //alignItems: "center",
  },
  title: {
    color: color.blackText,
    fontSize: windowWidth * 0.05163,
    fontFamily: 'CenturyGothic',
    fontWeight: '300',
    marginTop: windowWidth * 0.036,
    marginLeft: windowWidth * 0.06,
  },
  cardView: {
    marginHorizontal: windowWidth * 0.036,
    borderRadius: windowWidth * 0.0316,
  },
  innerCardView: {
    backgroundColor: 'white',
    flexDirection: 'column',
    padding: windowWidth * 0.01,
    paddingHorizontal: windowWidth * 0.036,
    borderRadius: windowWidth * 0.0316,
    minHeight: windowWidth * 0.1663,
    justifyContent: 'center',
  },
  cardSubContainer: {flexDirection: 'row', alignItems: 'center'},
  titleView: {
    flex: 1,
    paddingLeft: windowWidth * 0.0369,
    width: windowWidth / 6,
  },
  leftContainImage: {
    height: windowWidth * 0.07146,
    width: windowWidth * 0.07146,
    alignSelf: 'center',
  },
  rightContainImage: {
    height: windowWidth * 0.0613,
    width: windowWidth * 0.0613,
    alignSelf: 'center',
  },
  titleStyle: {
    color: color.blackText,
    fontSize: windowWidth * 0.0416,
    fontFamily: 'CenturyGothic',
    //marginTop: windowWidth * 0.016,
  },
  textStyle: {
    color: color.appGreen,
    fontSize: windowWidth * 0.036,
    fontFamily: 'CenturyGothic',
    // textAlign: 'justify',
    // marginTop: windowWidth * 0.0116,
  },
  iconView: {
    width: windowWidth * 0.096,
    height: windowWidth * 0.096,
    borderRadius: (windowWidth * 0.196) / 2,
    //borderWidth: 0.6,
    borderColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
  },
  creditCardTitle: {
    color: color.lightGrey,
    fontSize: windowWidth * 0.0416,
    fontFamily: 'CenturyGothic',
  },
  creditCardText: {
    color: color.lightGrey,
    fontSize: windowWidth * 0.0366,
    fontFamily: 'CenturyGothic',
    textAlign: 'justify',
  },
  smallTitle: {
    color: color.lightGrey,
    fontSize: windowWidth * 0.031,
    fontFamily: 'CenturyGothic',
    textAlign: 'justify',
  },
  letterTitle: {
    color: color.textColor,
    fontSize: windowWidth * 0.04636,
    fontFamily: 'CenturyGothic-Bold',
    alignSelf: 'center',
  },
  activeListView: {
    backgroundColor: 'transparent',
    width: windowWidth * 0.194,
    height: windowWidth * 0.1941,
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 5
  },
  activeListName: {
    color: 'black',
    fontSize: windowWidth * 0.036,
    fontFamily: 'CenturyGothic',
    alignSelf: 'center'
  },
  listImageView: {
    width: windowWidth / 4,
    // height: windowWidth / 4.49,
    borderWidth: 0,
    //justifyContent: 'space-around',
    //margin: windowWidth * 0.0096,
    borderRadius: windowWidth * 0.0196,
    alignItems: 'flex-start',
    //marginRight: 4,
    //backgroundColor:'red'
  },
  videoRowTitle: {
    color: 'white',
    fontSize: windowWidth * 0.0436,
    fontFamily: 'CenturyGothic-bold',
    textShadowColor: 'black',
    textShadowOffset: {width: 0.136, height: 0.136},
    textShadowRadius: 1,
  },
  matchListTitle: {
    color: color.blackText,
    fontSize: windowWidth * 0.0496,
    fontFamily: 'CenturyGothic',
    margin: windowWidth * 0.046,
    marginRight: windowWidth * 0.0136,
    fontWeight: '400',
  },
  smallCircle: {
    backgroundColor: color.secondaryColor,
    height: windowWidth * 0.06,
    width: windowWidth * 0.06,
    borderRadius: (windowWidth * 0.06) / 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: windowWidth * 0.046,
  },
  matchCount: {
    color: color.text,
    fontSize: windowWidth * 0.0436,
    fontFamily: 'CenturyGothic',
    fontWeight: '400',
  },
  CommunityContainer: {flexDirection: 'column', padding: windowWidth * 0.06},
  communityImage: {
    width: windowWidth / 3.16,
    height: windowWidth / 3.16,
    borderRadius: windowWidth * 0.0196,
    marginRight: windowWidth * 0.0136,
    borderWidth: 0.36,
  },
  topSpaceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: windowWidth * 0.036,
  },
  communitySubTitle: {
    color: color.blackText,
    fontSize: windowWidth * 0.0436,
    fontFamily: 'CenturyGothic',
  },
  viewAlltext: {
    color: '#deb686',
    fontSize: windowWidth * 0.04136,
    fontFamily: 'CenturyGothic-Bold',
  },
  tagView: {
    backgroundColor: '#e1e4eb',
    margin: windowWidth * 0.0136,
    borderRadius: windowWidth * 0.0136,
  },
  tagText: {
    color: color.blackText,
    fontSize: windowWidth * 0.036,
    fontFamily: 'CenturyGothic',
    margin: windowWidth * 0.036,
  },
  IconCircle: {
    width: windowWidth * 0.076,
    height: windowWidth * 0.076,
    borderRadius: (windowWidth * 0.076) / 2,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoListIcon: {
    width: windowWidth * 0.046,
    height: windowWidth * 0.046,
  },
  videoAuthorName: {
    color: 'white',
    fontSize: windowWidth * 0.0376,
    fontFamily: 'CenturyGothic-bold',
    textShadowColor: 'black',
    textShadowOffset: {width: 0.136, height: 0.136},
    textShadowRadius: 1,
    alignSelf: 'center',
    marginLeft: windowWidth * 0.0136,
  },
  durationIcon: {
    width: windowWidth * 0.0436,
    height: windowWidth * 0.0436,
    borderRadius: (windowWidth * 0.0436) / 2,
    marginHorizontal: windowWidth * 0.0136,
  },
  durationView: {
    borderRadius: (windowWidth * 0.946) / 2,
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  durationText: {
    color: color.blackText,
    fontSize: windowWidth * 0.0376,
    fontFamily: 'CenturyGothic',
    alignSelf: 'center',
    marginRight: windowWidth * 0.0136,
  },
  startIcon: {
    color: color.secondaryColor,
    fontSize: windowWidth * 0.056,
    marginHorizontal: windowWidth * 0.036,
  },
  inActiveStar: {
    color: color.blackText,
    fontSize: windowWidth * 0.056,
    marginHorizontal: windowWidth * 0.0316,
  },
});
