import { StyleSheet, Dimensions } from "react-native";
const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;
import { color } from "../../theme";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.whiteText,
    //justifyContent: "center",
    //alignItems: "center",
  },
  logo: {
    width: windowWidth / 2.6,
    height: windowWidth / 2.6,
    marginBottom: 6,
  },
  collapsibleLabel: {
    color: color.blackText,
    fontFamily: "CenturyGothic-Bold",
    fontSize: windowWidth * 0.046,
  },
  personalDetailsContainer: {
    width: windowWidth,
    paddingBottom: windowWidth * 0.096,
    borderBottomColor: color.lightGrey,
    borderBottomWidth: 0,
    elevation: 0,
  },
  inputStyle: {},
  documentsContainer: {
    width: windowWidth,
    borderBottomColor: color.lightGrey,
    borderBottomWidth: 0,
    elevation: 0,
  },
  docSubContainer: { paddingVertical: windowWidth * 0.06 },
  showDataContainer: { height: 0 },
  datePicker: {
    borderTopWidth: 0,
    borderStyle: null,
    borderRadius: 0,
    height: windowWidth * 0.15,
    width: windowWidth * 0.884,
    backgroundColor: "transparent",
    marginHorizontal: windowWidth * 0.1,
    marginLeft: windowWidth * 0.061,
    marginTop: windowWidth * 0.01,
    borderBottomWidth: 2.1,
    borderColor: color.lineColor,
    marginBottom: windowWidth * 0.069,
  },
  datePickerInput: {
    backgroundColor: "transparent",
    top: 0,
    bottom: 0,
    height: windowHeight / 15.6,
    minHeight: 44,
    minWidth: windowWidth / 3.6,
    width: 10,
    borderRadius: 0,
    borderWidth: 0,
    borderColor: color.lineColor,
    color: "pink",
    fontSize: windowWidth * 0.04169,
    marginTop: windowWidth * 0.076,
    alignItems: "flex-start",
    paddingLeft: windowWidth * 0.016,
    //fontFamily: "OpenSans",
  },
  checkBoxContainer: {
    flexDirection: "row",
    paddingHorizontal: windowWidth * 0.06,
    marginTop: windowWidth * 0.069,
  },
  selectcheckBoxContainer: {
    flexDirection: "row",
    paddingHorizontal: windowWidth * 0.06,
  },
  checkBox: {
    width: windowWidth * 0.09,
    height: windowWidth * 0.09,
  },
  checkBoxText: {
    fontSize: windowWidth * 0.0416,
    //marginLeft: windowWidth * 0.01,
    marginTop: windowWidth * 0.0106,
    color: color.lightGrey,
    fontFamily: "CenturyGothic",
  },
  button: {
    width: windowWidth / 1.9,
    height: windowWidth * 0.156,
    borderRadius: windowWidth * 0.076,
    marginTop: windowWidth * 0.06,
    alignSelf: "center",
  },
  plainbutton: {
    width: windowWidth / 1.9,
    height: windowWidth * 0.156,
    borderRadius: windowWidth * 0.076,
    alignSelf: "center",
    marginTop: windowWidth * 0.109,
    backgroundColor: "white",
    borderWidth: 1,
  },
  buttonText: {
    color: "white",
    fontSize: windowWidth * 0.0419,
    alignSelf: "center",
    fontFamily: "CenturyGothic-Bold",
  },
  dataInputStyle: { marginBottom: windowWidth * 0.036 },
  notesContainer: {
    width: windowWidth,
    borderBottomColor: color.lightGrey,
    borderBottomWidth: 0,
    elevation: 0,
  },
  noteHeader: {
    color: color.blackText,
    fontFamily: "CenturyGothic-Bold",
    fontSize: windowWidth * 0.046,
    paddingVertical: windowWidth * 0.036,
    marginLeft: windowWidth * 0.06,
  },
  notesText: {
    color: color.blackText,
    fontFamily: "CenturyGothic",
    fontSize: windowWidth * 0.0416,
    paddingVertical: windowWidth * 0.016,
    marginLeft: windowWidth * 0.0516,
  },
  notesInputStyle: {},
  notesCountText: {
    fontFamily: "CenturyGothic",
    color: color.lightGrey,
    alignSelf: "flex-end",
    fontSize: windowWidth * 0.036,
    marginRight: windowWidth * 0.06,
    marginBottom: windowWidth * 0.06,
  },
  previewHeader: {
    color: color.blackText,
    fontFamily: "CenturyGothic-Bold",
    fontSize: windowWidth * 0.046,
    paddingVertical: windowWidth * 0.036,
    marginLeft: windowWidth * 0.06,
  },
  previewText: {
    color: color.blackText,
    fontFamily: "CenturyGothic",
    fontSize: windowWidth * 0.0416,
    paddingVertical: windowWidth * 0.036,
    marginLeft: windowWidth * 0.06,
  },
  modalBox: {
    width: windowWidth / 1.264,
    backgroundColor: "white",
    padding: windowWidth * 0.06,
    borderRadius: windowWidth * 0.0164,
    alignSelf: "center",
  },
  modalView: {
    flexDirection: "row",
    backgroundColor: "white",
    padding: windowWidth * 0.0146,
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalSuccessIcon: {
    color: "#39b54a",
    fontSize: windowWidth * 0.116,
    alignSelf: "center",
    marginBottom: windowWidth * 0.016,
  },
  modalSuccessText: {
    fontSize: windowWidth * 0.06,
    fontFamily: "CenturyGothic",
    color: "#39b54a",
    textAlign: "center",
    marginBottom: windowWidth * 0.06,
  },
  modalCenterText: {
    fontSize: windowWidth * 0.0416,
    fontFamily: "CenturyGothic",
    color: "black",
    textAlign: "center",
    marginHorizontal: windowWidth * 0.0416,
  },
  modalImage: {
    width: windowWidth * 0.09,
    height: windowWidth * 0.09,
    alignSelf: "flex-end",
  },
  modalButton: {
    backgroundColor: color.primary,
    justifyContent: "center",
    paddingVertical: windowWidth * 0.036,
    borderRadius: windowWidth * 0.0164,
    marginTop: windowWidth * 0.01694,
  },
  modalButtonText: {
    fontSize: windowWidth * 0.0436,
    fontFamily: "CenturyGothic",
    color: "black",
    //alignSelf: "center",
    alignSelf: "center",
  },
});
